### PR TITLE
PR for #3: Changing sample to run regression

### LINKED ISSUE #3: Run regression on a restricted sample
In this issue, we will track the results of regressions when we change the sample to dates after 1960

### PR DESCRIPTION
**Pull request by Erick11293**
Closes #3 

I've changed the sample to be equal or greater than 1960 and I've run the run_all to create all the outputs.

Codes:
- [analyze_data.py](https://github.com/Erick11293/template/blob/d82629aa2da6dd2732609f506eca77b0da0785a2/analysis/code/analyze_data.py)
- [make.py](https://github.com/Erick11293/template/blob/9ca4c086b5cb0cb539ac1f7d805cfdabbb4c0024/paper_slides/make.py)
- [paper.lyx](https://github.com/Erick11293/template/blob/9ca4c086b5cb0cb539ac1f7d805cfdabbb4c0024/paper_slides/code/paper.lyx)

Deliverables:
- [Paper](https://github.com/Erick11293/template/blob/d82629aa2da6dd2732609f506eca77b0da0785a2/paper_slides/output/paper.pdf)

### CODE REVIEW

**Comment by jc-cisneros** [comment]
Thanks @Erick11293! Some comments:
1) As in #2, you can mention which scripts were modified and add the deliverables to the description of the PR (or link the [deliverables from the issue](https://github.com/Erick11293/template/issues/3#issuecomment-1640712876)).
2) Recall that the task is to "export the model coefficient, standard errors and p-value into a new table output". The table you have in the [paper](https://github.com/Erick11293/template/blob/d82629aa2da6dd2732609f506eca77b0da0785a2/paper_slides/output/paper.pdf) is correct, but you also want to keep the previous table.

Let me know if you have any questions/comments, @Erick11293.

**Comment by jc-cisneros** [comment]
Hi @Erick11293! You need a new table that you can create on LyX and fill using `tablefill`.

**Comment by Erick11293** [comment]
Hi @jc-cisneros . I've done the changes.

**Review by jc-cisneros — APPROVED** [review]
Thanks @Erick11293! The changes reflected in [the paper](https://github.com/Erick11293/template/blob/9ca4c086b5cb0cb539ac1f7d805cfdabbb4c0024/paper_slides/output/paper.pdf) are correct. I approve the merge to `master`.

As next steps you should complete the merge from #2, update this development branch from `master`, re-run the repo, and merge back to `master` (at the end of this process we should have the changes from both issue reflected on `master`). Thanks again!

**Pull request merged**
